### ISSUE TITLE
Docker-free deploy instruction

### ISSUE THREAD

**Issue by hograthm** [Floens/uchan#11]
self-explaining

**Comment by Floens** [comment]
This was the guide https://github.com/Floens/uchan/blob/07b3a7d1587fe9cc1638481100a481f71dbd4b89/SETUP
It might not be completely complete now.

512MB also seems very small for uchan, postgres alone takes up a big chunk of that.

**Comment by RichardVoid** [comment]
Board population will be from 20 to 30 users with a small number of posts and media content.

**Comment by RichardVoid** [comment]
Can I change some backend components to reduce memory usage? For example, use Sqlite.

**Comment by Floens** [comment]
Not sure, there might be some postgres-only functionality used. You can omit varnish. 

You can also add the setting `bypass_worker = true` under `[app]` in `config.ini` to skip using workers entirely, omitting rabbitmq and the worker instances 🤔

**Comment by RichardVoid** [comment]
I will test and report the results in this issue. Thanks for help! 👌🐸
