### ISSUE TITLE
Bad referer header

### ISSUE THREAD

**Issue by RichardVoid** [Floens/uchan#2]
I tried to deploy as it was written in readme. In the config I wrote my keys for the reCAPTCHA and it seems they are working correctly. Imageboard has started with no warnings in logs and I created new mod. When I tried to login with my username, password and passed captcha I got `Bad referer header`.  
This error raised in [verify.py](https://github.com/Floens/uchan/blob/dev/uchan/view/verify.py#L16-L18), but I cant find where is `check_csrf_referer()` and what it does.

**Comment by Floens** [comment]
The referer check checks the header value of the referer to the site url. This is configured by the `site_url` config.
For example, if your site is reachable at https://uchan.example.com/ site_url would equal "https://uchan.example.com"

**Comment by RichardVoid** [comment]
Oh. Im retarded. Now everthing works.
