### ISSUE TITLE
Error Bad referer header

### ISSUE THREAD

**Issue by xoryouyou** [Floens/uchan#5]
Hi guys,

I've tried to setup the board via the provided docker script.

The first thing I had to to is to create the `database`, `log` and `media` folders manually in `./data` .

But after getting a recaptcha and running it on a test domain it always prompts me with the following:

```
Error
Bad referer header
```

at `/mod/auth` after trying to login (Tested chrome/firefox) .

It's running directly on port `1234` no nginx in between but I tried to set the `proxy_fixer_num_proxies` to 3 and uncommented the forwarding section in the `uchan.vcl`

Hopefully there is a fix for that.

Regards

**Comment by Floens** [comment]
See #2

**Comment by Floens** [comment]
Hmm that's strange. You could try to add a print statement to https://github.com/Floens/uchan/blob/dev/uchan/view/__init__.py#L106 to see what the referer is interpreted.

**Comment by xoryouyou** [comment]
Well it's giving me this:

![logs](https://user-images.githubusercontent.com/777569/38831201-eab0eb48-41be-11e8-9e36-691db4e585ce.PNG)

And I can't find a 'db' driver in the docker documentation.

I'll give it another try tomorrow :)

**Comment by Floens** [comment]
Did you figure this out?

I'm not sure what docker is saying with the db log driver, I have not seen that before.
You might want to look into `data/log/uchan.log` instead.

I also pushed a commit that logs the referer mismatch https://github.com/Floens/uchan/commit/b6c9b19d0134495a50964c4cbc5e4f3a99e9c420
